name: MP128SpecialPickaxe
version: '1.0-SNAPSHOT'
main: project128.minecraft.mP128SpecialPickaxe.MP128SpecialPickaxe
api-version: '1.18'
author: TheSpace
description: Плагин для режима Underground
commands:
  specialpickaxe:
    description: "Основная команда плагина"
    usage: "/command <arg>"
    aliases: [ sp ]
